<?php
/**
 * Resources hub template.
 *
 * @package WebStudioWA
 */

get_header();
?>
<section class="resources-hero"><div class="container resources-hero__grid"><div><p class="eyebrow"><?php esc_html_e('Web Studio WA Resources', 'winter'); ?></p><h1><?php esc_html_e('WordPress resources for safer, smarter websites', 'winter'); ?></h1><p><?php esc_html_e('Guides and practical notes on WordPress security, maintenance, accessibility, social feeds and plugin workflows for business websites.', 'winter'); ?></p></div><div class="resources-hero__visual" aria-label="<?php esc_attr_e('Web Studio WA resources library preview', 'winter'); ?>"><i></i><i></i><i></i><i></i></div></div></section>
<section class="section resources-categories"><div class="container section__heading"><p class="eyebrow"><?php esc_html_e('Browse by topic', 'winter'); ?></p><h2><?php esc_html_e('Practical resources for website care', 'winter'); ?></h2></div><div class="container resources-category-grid"><?php $categories = [['WordPress Security','Practical ways to reduce admin risk and improve website visibility.'],['WordPress Maintenance','Tips for updates, backups, content changes and ongoing website care.'],['WordPress Plugins','Guides for choosing, using and supporting WordPress plugin workflows.'],['SEO & Accessibility','Helpful notes for alt text, content structure and user-friendly websites.'],['Social Media Feeds','Explainers for Instagram, Facebook and API-based social feed display.'],['Website Care','Practical advice for keeping business websites useful and reliable.']]; foreach ($categories as [$title, $text]) : ?><article class="resource-card"><h3><?php echo esc_html($title); ?></h3><p><?php echo esc_html($text); ?></p></article><?php endforeach; ?></div></section>
<section class="section resources-articles"><div class="container section__heading"><p class="eyebrow"><?php esc_html_e('Planned articles', 'winter'); ?></p><h2><?php esc_html_e('Suggested articles to publish next', 'winter'); ?></h2></div><div class="container planned-article-grid"><?php $articles = [['WordPress Security','How to Check Who Can Edit Your WordPress Website','A practical starting point for reviewing website-changing access.'],['WordPress Security','Why WordPress Admin Access Should Be Reviewed Regularly','Why regular access reviews are a useful part of website care.'],['WordPress Security','How to Monitor WordPress 404 Errors Without a Heavy Plugin','What 404 patterns can tell you about a website without making claims they solve security.'],['WordPress Security','WordPress Admin vs Editor: What Access Should Staff Have?','A plain-language guide to choosing roles for staff and contractors.'],['WordPress Security','How to Reduce Risk When Giving Website Access to Contractors','Practical steps for safer access handovers.'],['WordPress Security','WordPress Security Checklist for Small Business Websites','A practical checklist for everyday website maintenance.'],['SEO & Accessibility','How to Find Images Missing Alt Text in WordPress','A simple guide to finding image gaps that affect accessibility.'],['SEO & Accessibility','Why Image Alt Text Matters for SEO and Accessibility','How useful alt text helps people and content quality.'],['SEO & Accessibility','WordPress Image SEO Checklist for Small Business Websites','A straightforward checklist for image preparation.'],['Social Media Feeds','Why Instagram and Facebook Feeds Stop Working on Websites','An introduction to API, permissions and connection changes.'],['Social Media Feeds','How to Add Social Feeds to WordPress Without Manual Tokens','Why guided OAuth connections can be more client-friendly.'],['Social Media Feeds','Meta App Review Explained for WordPress Website Owners','A plain-language explanation of review requirements.']]; foreach ($articles as [$category, $title, $summary]) : ?><article class="planned-article-card"><span><?php echo esc_html($category); ?></span><h3><?php echo esc_html($title); ?></h3><p><?php echo esc_html($summary); ?></p><small><?php esc_html_e('Planned article', 'winter'); ?></small></article><?php endforeach; ?></div></section>
<section class="resources-plugin-cta"><div class="container"><p class="eyebrow"><?php esc_html_e('Web Studio WA plugins', 'winter'); ?></p><h2><?php esc_html_e('Explore Web Studio WA plugins', 'winter'); ?></h2><p><?php esc_html_e('Our plugins are built from real website support needs, with a focus on practical admin workflows, clean display and ongoing maintenance.', 'winter'); ?></p><a class="button button--primary" href="<?php echo esc_url(home_url('/plugins/')); ?>"><?php esc_html_e('View WordPress plugins', 'winter'); ?></a></div></section>
<section class="resources-contact-cta"><div class="container"><p class="eyebrow"><?php esc_html_e('Practical website support', 'winter'); ?></p><h2><?php esc_html_e('Need help with your WordPress website?', 'winter'); ?></h2><p><?php esc_html_e('Web Studio WA can help with website maintenance, plugin setup, admin access reviews and practical improvements.', 'winter'); ?></p><a class="button button--primary" href="<?php echo esc_url(home_url('/contact/')); ?>"><?php esc_html_e('Contact Web Studio WA', 'winter'); ?></a></div></section>
<?php get_footer();
