<?php
/** Admin Watch Central landing page. @package WebStudioWA */
get_header();
$wordpress_url = 'https://wordpress.org/plugins/adminwatch-central/';
$support_url = 'https://wordpress.org/support/plugin/adminwatch-central/';
?>
<section class="admin-watch-hero"><div class="container admin-watch-hero__grid"><div class="admin-watch-hero__copy">
<p class="eyebrow"><?php esc_html_e('Visibility, not fear', 'winter'); ?></p>
<div class="admin-watch-brand"><img src="<?php echo esc_url(wswa_asset('img/admin-watch/admin-watch-icon.png')); ?>" alt="" width="1254" height="1254"><span><?php esc_html_e('Admin Watch Central', 'winter'); ?></span></div>
<h1><?php esc_html_e('Know who can change your WordPress website', 'winter'); ?></h1>
<p><?php esc_html_e('Admin Watch Central gives site owners and administrators a clearer view of website-changing access, recent login activity, session visibility and 404 patterns, without storing unnecessary sensitive data.', 'winter'); ?></p>
<div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View on WordPress.org', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url($support_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('Plugin support', 'winter'); ?></a></div>
</div><figure class="admin-watch-hero__visual"><img src="<?php echo esc_url(wswa_asset('img/admin-watch/admin-watch-team-dashboard.svg')); ?>" alt="<?php esc_attr_e('Business owner reviewing website access and recent activity in the Admin Watch Central dashboard', 'winter'); ?>" width="920" height="680"></figure></div></section>

<section class="section admin-watch-intro"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('A calmer admin routine', 'winter'); ?></p><h2><?php esc_html_e('A clearer view for the people responsible for your website', 'winter'); ?></h2><p><?php esc_html_e('Admin Watch Central brings useful access and activity signals into one focused WordPress dashboard, so routine checks feel more straightforward and support conversations have better context.', 'winter'); ?></p></div></section>

<section class="section admin-watch-features"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Dashboard visibility', 'winter'); ?></p><h2><?php esc_html_e('What Admin Watch helps you review', 'winter'); ?></h2></div><div class="container admin-watch-feature-grid"><?php $features = [['Website-changing users','See users with roles that can change website settings, pages or plugins.'],['Latest successful logins','Review recent successful logins for users who can manage or edit the website.'],['Password change visibility','See when user passwords were last changed where WordPress makes that information available.'],['Password strength estimate','View a local strength estimate to help identify weak password habits.'],['MFA visibility','Show MFA status when supported by compatible two-factor plugins.'],['Active sessions','Get visibility of active WordPress sessions without storing tokens.'],['404 monitor','Review front-end 404 activity patterns with retention controls.'],['Privacy-conscious design','No IP addresses, session tokens or user agents are stored by the plugin.']]; foreach ($features as $index => [$title, $text]) : ?><article><span><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></span><h3><?php echo esc_html($title); ?></h3><p><?php echo esc_html($text); ?></p></article><?php endforeach; ?></div></section>

<section class="section admin-watch-shots"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Plugin interface', 'winter'); ?></p><h2><?php esc_html_e('Designed for useful checks, not dashboard clutter', 'winter'); ?></h2></div><div class="container admin-watch-shot-grid"><?php $screens = [['Dashboard overview', 'Site health · access · latest activity'], ['Users & Access', 'Roles · password changes · MFA'], ['Active Sessions', 'Current sessions · review context'], ['404 Monitor', 'Recent patterns · retention controls'], ['Settings', 'Privacy tools · helpful preferences']]; foreach ($screens as $index => [$title, $label]) : ?><article class="admin-watch-shot admin-watch-shot--<?php echo esc_attr((string) ($index + 1)); ?>"><div class="admin-watch-shot__ui"><div class="admin-watch-shot__top"><i></i><i></i><i></i></div><strong><?php echo esc_html($title); ?></strong><span></span><div class="admin-watch-shot__tiles"><i></i><i></i><i></i></div></div><h3><?php echo esc_html($title); ?></h3><p><?php echo esc_html($label); ?></p></article><?php endforeach; ?></div></section>

<section class="section admin-watch-process"><div class="container admin-watch-process__grid"><div class="admin-watch-heading"><p class="eyebrow"><?php esc_html_e('How it works', 'winter'); ?></p><h2><?php esc_html_e('Simple visibility for everyday admin routines', 'winter'); ?></h2></div><ol><?php $steps = ['Install the plugin from WordPress.org', 'Open Admin Watch Central in your dashboard', 'Review access, sessions and 404 activity', 'Use the information to improve admin routines and support decisions']; foreach ($steps as $index => $step) : ?><li><span><?php echo esc_html((string) ($index + 1)); ?></span><p><?php echo esc_html($step); ?></p></li><?php endforeach; ?></ol></div></section>

<section class="section admin-watch-privacy"><div class="container admin-watch-privacy__grid"><div><p class="eyebrow"><?php esc_html_e('Privacy and safety', 'winter'); ?></p><h2><?php esc_html_e('Built with privacy in mind', 'winter'); ?></h2><p><?php esc_html_e('Visibility should be useful without collecting more information than it needs to.', 'winter'); ?></p></div><ul><li><?php esc_html_e('No IP addresses stored', 'winter'); ?></li><li><?php esc_html_e('No session tokens stored', 'winter'); ?></li><li><?php esc_html_e('No user agents stored', 'winter'); ?></li><li><?php esc_html_e('Privacy exporter and eraser support', 'winter'); ?></li><li><?php esc_html_e('Retention settings for 404 data', 'winter'); ?></li><li><?php esc_html_e('Designed to support admin visibility, not replace a full security suite', 'winter'); ?></li></ul></div></section>

<section class="section admin-watch-audience"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Who it is for', 'winter'); ?></p><h2><?php esc_html_e('Useful for site owners, admins and small agencies', 'winter'); ?></h2></div><div class="container admin-watch-audience__grid"><?php foreach (['Business website owners', 'WordPress administrators', 'Small web agencies', 'Website care and maintenance teams'] as $audience) : ?><article><h3><?php echo esc_html($audience); ?></h3></article><?php endforeach; ?></div></section>

<section class="section admin-watch-download"><div class="container"><p class="eyebrow"><?php esc_html_e('Free WordPress plugin', 'winter'); ?></p><h2><?php esc_html_e('Available on WordPress.org', 'winter'); ?></h2><p><?php esc_html_e('Admin Watch Central is available as a free WordPress plugin.', 'winter'); ?></p><div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View on WordPress.org', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url($support_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('Support forum', 'winter'); ?></a></div></div></section>

<section class="section admin-watch-faq"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('FAQ', 'winter'); ?></p><h2><?php esc_html_e('Questions about Admin Watch Central', 'winter'); ?></h2></div><div class="container admin-watch-faq__grid"><?php $faqs = [['What is Admin Watch Central?', 'It is a WordPress plugin that provides admin visibility and review tools.'], ['Does it block attacks?', 'No. It supports visibility and review; it does not replace a full security stack.'], ['Does it store IP addresses?', 'No, the plugin does not store IP addresses.'], ['Does it store session tokens?', 'No, the plugin does not store session tokens or user agents.'], ['Does it work with two-factor authentication?', 'MFA status is available when supported by compatible two-factor plugins.'], ['Is it free?', 'Yes. Admin Watch Central is available free on WordPress.org.'], ['Where can I get support?', 'Support is available through the WordPress.org support forum.']]; foreach ($faqs as [$question, $answer]) : ?><article><h3><?php echo esc_html($question); ?></h3><p><?php echo esc_html($answer); ?></p></article><?php endforeach; ?></div></section>

<section class="admin-watch-cta"><div class="container"><p class="eyebrow"><?php esc_html_e('Web Studio WA', 'winter'); ?></p><h2><?php esc_html_e('Want better visibility of your WordPress admin area?', 'winter'); ?></h2><p><?php esc_html_e('Install Admin Watch Central or contact Web Studio WA if you need help reviewing WordPress access and maintenance routines.', 'winter'); ?></p><div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View plugin', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url(home_url('/contact/')); ?>"><?php esc_html_e('Contact Web Studio WA', 'winter'); ?></a></div></div></section>
<?php get_footer();
