<?php
/**
 * Admin Watch Central landing page.
 *
 * Applied to /plugins/admin-watch/ when Admin Watch is a child of Plugins.
 *
 * @package WebStudioWA
 */

get_header();
$wordpress_url = 'https://wordpress.org/plugins/adminwatch-central/';
$support_url = 'https://wordpress.org/support/plugin/adminwatch-central/';
$github_url = 'https://github.com/asankalk/admin-watch-free';
?>
<section class="admin-watch-hero">
    <div class="container admin-watch-hero__grid"><div>
        <p class="eyebrow"><?php esc_html_e('Web Studio WA Plugin', 'winter'); ?></p>
        <img class="admin-watch-logo" src="<?php echo esc_url(wswa_asset('img/admin-watch-logo.svg')); ?>" alt="<?php esc_attr_e('Admin Watch Central', 'winter'); ?>" width="360" height="82">
        <h1><?php esc_html_e('Admin Watch Central for WordPress', 'winter'); ?></h1>
        <p><?php esc_html_e('A simple WordPress admin visibility plugin that helps you review user access, login activity, active sessions and 404 activity from one clean dashboard.', 'winter'); ?></p>
        <div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View on WordPress.org', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url($support_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('Plugin support', 'winter'); ?></a></div>
        <a class="admin-watch-github" href="<?php echo esc_url($github_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View GitHub', 'winter'); ?></a>
    </div><div class="admin-watch-dashboard" aria-label="<?php esc_attr_e('Admin Watch Central dashboard preview', 'winter'); ?>"><div class="admin-watch-dashboard__bar"><span></span><span></span><span></span><strong>Admin Watch Central</strong></div><div class="admin-watch-dashboard__grid"><article><b><?php esc_html_e('Site Health', 'winter'); ?></b><i></i><small><?php esc_html_e('Review dashboard', 'winter'); ?></small></article><article><b><?php esc_html_e('Website Access', 'winter'); ?></b><i></i><small><?php esc_html_e('Users & roles', 'winter'); ?></small></article><article><b><?php esc_html_e('Active Sessions', 'winter'); ?></b><i></i><small><?php esc_html_e('Session overview', 'winter'); ?></small></article><article><b><?php esc_html_e('404 Errors', 'winter'); ?></b><i></i><small><?php esc_html_e('Recent patterns', 'winter'); ?></small></article></div></div></div>
</section>

<section class="section admin-watch-intro"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Visibility, not fear', 'winter'); ?></p><h2><?php esc_html_e('Know who can change your WordPress website', 'winter'); ?></h2><p><?php esc_html_e('Admin Watch Central gives site owners and administrators a clearer view of website-changing access, recent login activity, session visibility and 404 patterns, without storing unnecessary sensitive data.', 'winter'); ?></p></div></section>

<section class="section admin-watch-features"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Dashboard visibility', 'winter'); ?></p><h2><?php esc_html_e('What Admin Watch helps you review', 'winter'); ?></h2></div><div class="container admin-watch-feature-grid"><?php $features = [['Admin and editor access','See users with website-changing roles so access reviews are easier.'],['Latest successful logins','Review recent login activity for users who can manage or edit the website.'],['Password change visibility','See when user passwords were last changed where WordPress makes that information available.'],['Password strength estimate','View a local strength estimate to help identify weak password habits.'],['MFA visibility','Show MFA status when supported by compatible two-factor plugins.'],['Active Sessions','Get visibility of active WordPress sessions without storing tokens.'],['404 Monitor','Review front-end 404 activity patterns with retention controls.'],['Privacy-conscious design','No IP addresses, session tokens or user agents are stored by the plugin.']]; foreach ($features as [$title, $text]) : ?><article><h3><?php echo esc_html($title); ?></h3><p><?php echo esc_html($text); ?></p></article><?php endforeach; ?></div></section>

<section class="section admin-watch-shots"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Plugin interface', 'winter'); ?></p><h2><?php esc_html_e('Designed for a clean WordPress admin experience', 'winter'); ?></h2></div><div class="container admin-watch-shot-grid"><?php foreach (['Dashboard overview','Users & Access','404 Monitor','Settings'] as $title) : ?><article><div class="admin-watch-shot__ui"><span></span><span></span><i></i><i></i><i></i></div><h3><?php echo esc_html($title); ?></h3><small><?php esc_html_e('Screenshot coming soon', 'winter'); ?></small></article><?php endforeach; ?></div></section>

<section class="section admin-watch-process"><div class="container admin-watch-process__grid"><div class="admin-watch-heading"><p class="eyebrow"><?php esc_html_e('How it works', 'winter'); ?></p><h2><?php esc_html_e('Simple visibility for everyday admin routines', 'winter'); ?></h2></div><ol><?php $steps = ['Install the plugin from WordPress.org','Open Admin Watch Central in your dashboard','Review access, sessions and 404 activity','Use the information to improve admin routines and support decisions']; foreach ($steps as $index => $step) : ?><li><span><?php echo esc_html((string) ($index + 1)); ?></span><p><?php echo esc_html($step); ?></p></li><?php endforeach; ?></ol></div></section>

<section class="section admin-watch-privacy"><div class="container admin-watch-privacy__grid"><div><p class="eyebrow"><?php esc_html_e('Privacy and safety', 'winter'); ?></p><h2><?php esc_html_e('Built with privacy in mind', 'winter'); ?></h2></div><ul><li><?php esc_html_e('No IP addresses stored', 'winter'); ?></li><li><?php esc_html_e('No session tokens stored', 'winter'); ?></li><li><?php esc_html_e('No user agents stored', 'winter'); ?></li><li><?php esc_html_e('Privacy exporter and eraser support', 'winter'); ?></li><li><?php esc_html_e('Retention settings for 404 data', 'winter'); ?></li><li><?php esc_html_e('Designed to support admin visibility, not replace a full security suite', 'winter'); ?></li></ul></div></section>

<section class="section admin-watch-audience"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('Who it is for', 'winter'); ?></p><h2><?php esc_html_e('Useful for site owners, admins and small agencies', 'winter'); ?></h2></div><div class="container admin-watch-audience__grid"><?php foreach (['Business website owners','WordPress administrators','Small web agencies','Website care and maintenance teams'] as $audience) : ?><article><h3><?php echo esc_html($audience); ?></h3></article><?php endforeach; ?></div></section>

<section class="section admin-watch-download"><div class="container"><p class="eyebrow"><?php esc_html_e('Free WordPress plugin', 'winter'); ?></p><h2><?php esc_html_e('Available on WordPress.org', 'winter'); ?></h2><p><?php esc_html_e('Admin Watch Central is available as a free WordPress plugin.', 'winter'); ?></p><div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View on WordPress.org', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url($support_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('Support forum', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url($github_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('GitHub', 'winter'); ?></a></div></div></section>

<section class="section admin-watch-faq"><div class="container section__heading admin-watch-heading"><p class="eyebrow"><?php esc_html_e('FAQ', 'winter'); ?></p><h2><?php esc_html_e('Questions about Admin Watch Central', 'winter'); ?></h2></div><div class="container admin-watch-faq__grid"><?php $faqs = [['What is Admin Watch Central?','It is a WordPress plugin that provides admin visibility and review tools.'],['Does it block attacks?','No. It supports visibility and review; it does not replace a full security stack.'],['Does it store IP addresses?','No, the plugin does not store IP addresses.'],['Does it store session tokens?','No, the plugin does not store session tokens or user agents.'],['Does it work with two-factor authentication?','MFA status is available when supported by compatible two-factor plugins.'],['Is it free?','Yes. Admin Watch Central is available free on WordPress.org.'],['Where can I get support?','Support is available through the WordPress.org support forum.']]; foreach ($faqs as [$question, $answer]) : ?><article><h3><?php echo esc_html($question); ?></h3><p><?php echo esc_html($answer); ?></p></article><?php endforeach; ?></div></section>

<section class="admin-watch-cta"><div class="container"><p class="eyebrow"><?php esc_html_e('Web Studio WA', 'winter'); ?></p><h2><?php esc_html_e('Want better visibility of your WordPress admin area?', 'winter'); ?></h2><p><?php esc_html_e('Install Admin Watch Central or contact Web Studio WA if you need help reviewing WordPress access and maintenance routines.', 'winter'); ?></p><div class="hero__actions"><a class="button button--primary" href="<?php echo esc_url($wordpress_url); ?>" target="_blank" rel="noopener noreferrer"><?php esc_html_e('View plugin', 'winter'); ?></a><a class="button button--ghost" href="<?php echo esc_url(home_url('/contact/')); ?>"><?php esc_html_e('Contact Web Studio WA', 'winter'); ?></a></div></div></section>
<?php get_footer();
